name: Assets

on:
  release:
    types:
    - created
  pull_request:

env:
  CMAKE_VERSION: '3.19.2'
  ARROW_VERSION: '3.0.0'
  PULSAR_VERSION: '2.7.0'

jobs:
  archive:
    name: Linux
    runs-on: ubuntu-latest
    container: centos:7
    steps:
    - name: Install dependencies
      run: |
        yum install -y epel-release centos-release-scl
        yum install -y curl make devtoolset-9-gcc-c++ rpm-build git
    - name: Install CMake
      run: curl -L https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz | tar xz --strip-components=1 -C /usr
    - name: Install Apache Arrow
      run: |
        yum install -y https://apache.bintray.com/arrow/centos/$(cut -d: -f5 /etc/system-release-cpe)/apache-arrow-release-latest.rpm
        yum install -y arrow-devel-$ARROW_VERSION-1.el7
    - name: Install Apache Pulsar
      run: |
        yum localinstall -y https://downloads.apache.org/pulsar/pulsar-$PULSAR_VERSION/RPMS/apache-pulsar-client-$PULSAR_VERSION-1.x86_64.rpm
        yum localinstall -y https://downloads.apache.org/pulsar/pulsar-$PULSAR_VERSION/RPMS/apache-pulsar-client-devel-$PULSAR_VERSION-1.x86_64.rpm
    - uses: actions/checkout@v2
    - name: Package
      run: |
        source /opt/rh/devtoolset-9/enable
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j package
    - id: tarball
      run: echo "##[set-output name=name;]$(ls bolson*.tar.gz)"
    - name: Install
      run: tar xvfz ./${{ steps.tarball.outputs.name }} -C /usr
    - name: Upload tarball
      uses: actions/upload-release-asset@v1
      if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.tarball.outputs.name }}
        asset_name: ${{ steps.tarball.outputs.name }}
        asset_content_type: application/octet-stream

  centos:
    name: CentOS
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
        - 7
        - 8
    container: centos:${{ matrix.version }}
    steps:
    - name: Install dependencies
      run: |
        yum install -y epel-release centos-release-scl
        yum install -y curl make rpm-build devtoolset-9-gcc-c++ git
    - name: Install CMake
      run: curl -L https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-Linux-x86_64.tar.gz | tar xz --strip-components=1 -C /usr
    - name: Install Apache Arrow
      if: ${{ matrix.version == '7' }}
      run: |
        yum install -y https://apache.bintray.com/arrow/centos/$(cut -d: -f5 /etc/system-release-cpe)/apache-arrow-release-latest.rpm
        yum install -y arrow-devel-$ARROW_VERSION-1.el${{ matrix.version }}
    - name: Install Apache Arrow
      if: ${{ matrix.version == '8' }}
      run: |
        dnf install -y https://apache.bintray.com/arrow/centos/$(cut -d: -f5 /etc/system-release-cpe | cut -d. -f1)/apache-arrow-release-latest.rpm
        dnf config-manager --set-enabled epel || :
        dnf config-manager --set-enabled powertools || :
        dnf config-manager --set-enabled codeready-builder-for-rhel-$(cut -d: -f5 /etc/system-release-cpe | cut -d. -f1)-rhui-rpms || :
        subscription-manager repos --enable codeready-builder-for-rhel-$(cut -d: -f5 /etc/system-release-cpe | cut -d. -f1)-$(arch)-rpms || :
        dnf install -y arrow-devel-$ARROW_VERSION-1.el${{ matrix.version }}
    - name: Install Apache Pulsar
      run: |
        yum localinstall -y https://downloads.apache.org/pulsar/pulsar-$PULSAR_VERSION/RPMS/apache-pulsar-client-$PULSAR_VERSION-1.x86_64.rpm
        yum localinstall -y https://downloads.apache.org/pulsar/pulsar-$PULSAR_VERSION/RPMS/apache-pulsar-client-devel-$PULSAR_VERSION-1.x86_64.rpm
    - uses: actions/checkout@v2
    - name: Package
      run: |
        source /opt/rh/devtoolset-9/enable
        cmake -DCMAKE_BUILD_TYPE=Release .
        make -j package
    - id: rpm
      run: echo "##[set-output name=name;]$(ls bolson*.rpm)"
    - name: Install
      run: yum localinstall -y ./${{ steps.rpm.outputs.name }}
    - name: Upload rpm
      uses: actions/upload-release-asset@v1
      if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.rpm.outputs.name }}
        asset_name: ${{ steps.rpm.outputs.name }}
        asset_content_type: application/octet-stream
  
  ubuntu:
    name: Ubuntu
    strategy:
      matrix:
        version:
        - 18.04
        - 20.04
    runs-on: ubuntu-${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Apache Arrow
      run: |
        wget https://apache.bintray.com/arrow/$(lsb_release --id --short | tr 'A-Z' 'a-z')/apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo apt-get install -y ./apache-arrow-archive-keyring-latest-$(lsb_release --codename --short).deb
        sudo apt-get update
        sudo apt-get install -y libarrow-dev=$ARROW_VERSION-1
    - name: Install Apache Pulsar
      run: |
        curl -L -O https://downloads.apache.org/pulsar/pulsar-$PULSAR_VERSION/DEB/apache-pulsar-client.deb
        sudo dpkg -i apache-pulsar-client.deb
        curl -L -O https://downloads.apache.org/pulsar/pulsar-$PULSAR_VERSION/DEB/apache-pulsar-client-dev.deb
        sudo dpkg -i apache-pulsar-client-dev.deb
    - name: Configure
      env:
        CC: gcc-9
        CXX: g++-9
      run: cmake -DCMAKE_BUILD_TYPE=Release .
    - name: Package
      run: make -j package
    - id: deb
      run: echo "##[set-output name=name;]$(ls bolson*.deb)"
    - name: Install
      run: sudo apt-get install -y ./${{ steps.deb.outputs.name }}
    - name: Upload deb
      uses: actions/upload-release-asset@v1
      if: ${{ github.event_name == 'release' && github.event.action == 'created' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ${{ steps.deb.outputs.name }}
        asset_name: ${{ steps.deb.outputs.name }}
        asset_content_type: application/octet-stream
