name: Documentation

on:
  push:
    branches:
    - master
  pull_request:
    paths:
    - 'doc/**'
    - 'src/**'
    - 'Doxyfile'
    - 'README.md'

jobs:
  book:
    name: Book
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: |
        mkdir -p $HOME/mdbook
        curl -L https://github.com/rust-lang/mdBook/releases/download/v0.4.7/mdbook-v0.4.7-x86_64-unknown-linux-gnu.tar.gz | tar xz -C $HOME/mdbook
        echo "${HOME}/mdbook/" >> $GITHUB_PATH
    - name: Install graphviz
      run: sudo apt-get install -y graphviz
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        default: true
    - uses: actions-rs/cargo@v1
      with:
        command: install
        args: --debug mdbook-graphviz
    - name: Build
      run: mdbook build
      working-directory: doc
    - uses: actions/upload-artifact@v2
      with:
        name: book
        path: doc/book
  
  cpp:
    name: 'C++'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install doxygen
      run: sudo apt-get install -y doxygen
    - name: Doxygen
      run: doxygen
    - uses: actions/upload-artifact@v2
      with:
        name: cpp
        path: doc/html

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [book, cpp]
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/download-artifact@v2
      with:
        name: book
    - uses: actions/download-artifact@v2
      with:
        name: cpp
        path: api/
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
